language: java
jdk:
        - openjdk8
addons:
        sonarcloud:
                organization: lorenzomei
                token:
                        secure: 4e4fc6ab727645cc72666e2eced67fee6f4e6a39
        apt:
                packages:
                        openjdk-8-jre-headless

notifications:
        slack:
                rooms:
                        - mjstudygroup:aroIFvc9nvH41hQM5lQ1gZon#ispw_project_code

before-install:
        - sudo apt-get update -q
        - sudo apt-get install ant-optional openjfx -y
script:
        - ant -v build test
        - sonar-scanner


